events {}

http {
    server {
        listen 80;

        # Route / to the Flask App
#        location / {
 #           proxy_pass http://flask-app:5000/;
  #          proxy_set_header Host $host;
   #         proxy_set_header X-Real-IP $remote_addr;
    #    }

        # Route /jenkins to Jenkins
        location /jenkins {
            proxy_pass http://jenkins:8080/jenkins;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
        }

        # Route /sonar to SonarQube
        location /sonar {
            proxy_pass http://sonarqube:9000/sonar;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route /grafana to Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
