name: Generic Task
description: Create a task for tracking a unit of work
labels: ["task"]
body:
  - type: textarea
    id: details
    attributes:
      label: Task Details
      description: Provide details about the task to be completed.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Acceptance Criteria
      description: Checklist of things to complete.
      options:
        - label: Item 1
        - label: Item 2