[app_server]
10.0.2.164 ansible_host=10.0.2.164

[app_server:vars]
ansible_user=ubuntu

ansible_ssh_private_key_file=/home/ridaz/.ssh/devops-project-key.pem

ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ridaz/.ssh/devops-project-key.pem -W %h:%p -q ubuntu@13.49.18.197"'